FROM jenkins/jenkins:lts
USER root
# Install Docker
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
RUN apt-get update && apt-get -y install docker-ce=5:19.03.13~3-0~debian-buster docker-ce-cli=5:19.03.13~3-0~debian-buster containerd.io
# Add Jenkins to group to run Docker commands
RUN usermod -aG docker jenkins
# Normally you would drop back to the regular jenkins user, for tutorial purposes we will not
# USER jenkins